zlib/Makefile
zlib/distinfo

Zlib just had two updates (one major and a quick bug fix update), you only have to pull the second patch.  The old version isn't available to download, so you need to update or change the url to somewhere it's archived.

zlib version update

---

libtremor/Makefile

#5 https://gitlab.xiph.org/xiph/tremor.git is the new git repo

updated libtremor git repo

---

libjpeg/Makefile
libjpeg/distinfo

I just rebuilt my environment and noticed that the jpegsrc v9c source as hosted doesn't build (SHA hash difference) and so I updated it to the v9d version which was updated on January 12th, 2021

libjpeg: update jpegsrc to v9d

---

freetype/Makefile

Disabled Brotli compression format dependency for WOFF2 fonts (enabled by default).

Fix building freetype

---

lua/files/KOSMakefile.mk

MacOS sed is fundamentally incompatible with GNU's, so the 32bit-mode macro replacement was causing build failures on MacOS. Changed to awk, tested on both platforms.

Fixed MacOS build by reverting sed command

---

freetype/Makefile

This fixes issue #16 where pkg-config is called and the build attempts to use the host's version of harfbuzz which attempts to link with pthread. Disabling it stops this search from occuring and allows the build to complete successfully.

FreeType: Disable building with harfbuzz

---

SDL/files/aica.c
libjpeg/files/jpeg.h
libjpeg/files/kos_img.c
libpng/files/kos_img.c
libtremor/files/README
libtremor/files/sndoggvorbis.c
scripts/lib.mk

We forgot to do this for kos-ports. It also needs to be done for the individual source repos as well.

Updated copyright information

---

libAL/Makefile
libAL/files/KOSMakefile.mk
libAL/pkg-descr

I'm not *totally* sure I've done this correctly - but this PR should add ALdc as libAL in kos-ports.

Add ALdc as libAL

---

zlib/Makefile
zlib/distinfo

zlib just had a new release and now the URL for the current 1.2.13 no longer successfully downloads. Updating zlib to 1.3 to fix it.

Update zlib to 1.3

---

libjimtcl/pkg-descr

Adding a `pkg-descr` file for [Jim Tcl](https://jim.tcl.tk/), using a summary extracted from the [official Wiki of Tcl](https://wiki.tcl-lang.org/page/What+is+Tcl).
Btw this file is required for [DreamSDK Manager](https://github.com/dreamsdk/manager).

`libjimtcl`: adding `pkg-descr` file.

---

micropython/pkg-descr

Adding a `pkg-descr` file for `micropython`, using a summary extracted from [GitHub](https://github.com/micropython/micropython).
Btw this file is required for [DreamSDK Manager](https://github.com/dreamsdk/manager).

`micropython`: adding `pkg-descr` file.

---

micropython/files/KOSMakefile.mk

Improves compatibility of **MicroPython** port on Windows and clean-up unnecessary files while installing the port.
- The `python3` executable will be tested to be sure if indeed, this binary can be used, if not, we will use `python` instead.
- Removes source files (`*.c`/`*.o`) from the `include` directory before installing the port. This will avoid to copy source files into the `include` directory, which is not necessary.

`MicroPython`: Improve compatibility on Windows + clean-up unnecessary files while installing

---

libGL/Makefile
libGL/files/KOSMakefile.mk
libGL/pkg-descr
libKGL/Makefile
libKGL/files/KOSMakefile.mk
libKGL/pkg-descr

This branch currently renames libGL (KallistiGL) to `libKGL` and adds @kazade's GLdc as the new `libGL`. 
I will create a KallistiOS branch which has all the `kgl` directory examples modified to link against `libKGL`, and meanwhile, we can port and create examples for GLdc within that branch. See the KallistiOS branch here: https://github.com/KallistiOS/KallistiOS/pull/353
When we are satisfied that GLdc is ready, we can remove all the KGL stuff from both branches and then merge them both.

Replace KallistiGL with GLdc as libGL

---

libjpeg/files/kos_img.c
libjpeg/files/kos_texture.c

Thanks to SWATs example here: https://github.com/DC-SWAT/DreamShell/blob/f4167ebed5e267f298dde4f8d1dc66e560541cca/lib/SDL_image/IMG_jpg.c#L465
Looks like there was a new scale property that we had to set.  Otherwise it would crash in libjpeg.

Fix libjpeg

---

mruby/Makefile
mruby/files/KOSMakefile.mk
mruby/pkg-descr

Adding **mruby** to KallistiOS Port, based on the excellent work of Yuji Yokoo (@yujiyokoo).
See [Dreamcast Wiki](https://dreamcast.wiki/Using_Ruby_for_Sega_Dreamcast_development) for more details.
[mruby](https://mruby.org/) is the lightweight implementation of the Ruby language complying with part of the ISO standard. mruby can be linked and embedded within your application.
2 examples provided by Yuji Yokoo (@yujiyokoo) will be added to KallistiOS as well.

Addition of `mruby` KallistiOS Port

---

libKGL/Makefile
libconio/Makefile
libdcplib/Makefile
libimageload/Makefile
libkmg/Makefile
libkosh/Makefile
libmodplug/Makefile
libmp3/Makefile
liboggvorbisplay/Makefile
libopusplay/Makefile
libparallax/Makefile
libpcx/Makefile
libtga/Makefile
libtsunami/Makefile

Retrieving any of the kos-ports from sf.net lately has been throwing this error:
```
Cloning into 'libkmg-2.0.0'...
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
At least 4 users have complained about the issue in the past day.
Given that @ljsebald added the ability to specify mirror URLs and uploaded Github-hosted mirrors, let's go ahead and add the URLs to the repo Makefiles.

Add Github mirror URLs to kos-hosted ports

---

lua/Makefile
lua/distinfo

SOMEHOW I completely and totally missed out on Lua5.4.5 and Lua5.4.6.... I have immediately rectified the problem and have updated our antique Lua version to the latest, testing that it looks good!
There are actually a bunch of minor bugfixes that have been added since these last two point versions:
https://www.lua.org/bugs.html#5.4.6

Updated Lua version from 5.4.4 to 5.4.6.

---

mruby/files/KOSMakefile.mk

`mruby`: checking if `/opt/toolchains/dc/bin` directory exists and create the path if needed

---

zlib/Makefile
zlib/distinfo

Hi,
I tried to compile the kos ports today and got a file size difference error during the compilation of the zlib library, therefore the build failed. I had a look at it and saw that there is a newer version of the zlib library and updated the library to 1.3.1. After using the new version, the compilation of the kos ports work again.

Update zlib to 1.3.1

---

stb_image/Makefile

Apparently comments in the recipe completely broke the makefile.  Tested and this compiles and works in my toolchain, just moving the comments to below the recipe block.

Fixed Makefile for stb_image

---

SDL_ttf/Makefile
SDL_ttf/pkg-descr

Since we already have freetype and SDL, this was quite simple. The only caveat, which might (more properly) need an update to the kos-ports scripts, is the header for it. Normally SDL_ttf.h is installed into the same folder as SDL's general headers. The kos-ports scripts have no functionality for this that I could find, so instead I pull the existing SDL headers into the SDL_ttf inst folder and re-link to it as SDL.
Some part of this also creates a duplicated inst/include/SDL/SDL_ttf.h
Hopefully someone may have some suggestions on how to clean that up a bit, but if not it still just works (if a bit messy).

Initial commit of SDL_ttf

---

SDL_ttf/Makefile
SDL_ttf/files/KOSMakefile.mk

The previous version worked as long as there was no ogl installed on the host system because autotools would believe that there was none available generally and not build the glfont example. The example relies on the glAttribute stack which we don't currently support in gldc.
If we ever do, then this should be updated to build that glfont examples and put it in the examples folder.

Updating SDL_ttf to not use autotools

---

cglm/Makefile
cglm/pkg-descr
expat/Makefile
freetype/Makefile
libchipmunk/Makefile
libchipmunk/pkg-descr
libcmark/Makefile
libcmark/pkg-descr
libyaml/Makefile
opus/Makefile
opusfile/Makefile
scripts/build.mk

This is a proposed update of the build.mk kos-ports scripts to allow cmake as an optional build system (alongside autotools). Instead of a flag for 'PORT_AUTOTOOLS', now there is a variable to set 'PORT_BUILD' that can be set to autotools or cmake (and would be open to expansion in the future).
I'm not very familiar with the way cmake works and I think that the values I'm passing in manually in build.mk may well belong more in the base cmake scripts since they would be global to the kos/kos-ports environment:
-DCMAKE_INSTALL_INCLUDEDIR=${KOS_PORTS}/${PORTNAME}/inst/include
-DCMAKE_INSTALL_LIBDIR=${KOS_PORTS}/${PORTNAME}/inst/lib 
Another thing is that this would, without some other work, make cmake a dependency for kos-ports. configure already is so perhaps that's not bad, but some help …

Update build to allow cmake, initial port of cglm

---

utils/build-all.sh
utils/calc_dist.py
utils/clean-all.sh
utils/uninstall-all.sh

kos-ports has always stopped building when one port fails to build.  Now we try and build everything first and then display errors at the end.  Example output:
```
------------------------------------------
1 Error(s) occurred during the build process:
/opt/toolchains/dc/kos/../kos-ports/mruby: Build failed with return code 2
```

Rework build-all.sh

---

libbearssl/Makefile
libbearssl/pkg-descr

As on the tin. Unfortunately don't have any sample use cases. It may be worthwhile to add an http(s)d example to go alongside httpd (or enhance it to optionally/additionally build with SSL if available)

Initial commit of BearSSL port

---

utils/build-all.sh

realpath does not work on MacOS without installing a brew package.  realpath was used to make:
/opt/toolchains/dc/kos/../kos-ports/mruby look like /opt/toolchains/dc/kos-ports/mruby 
A fix is available in the environ.sh file in KOS repo here: https://github.com/KallistiOS/KallistiOS/pull/556

realpath does not exist on mac

---

SDL_ttf/files/KOSMakefile.mk

I had to make sure to tack in on in the KOSMakefile here, now with https://github.com/KallistiOS/KallistiOS/pull/569 it's not necessary as it's automatically provided.

Remove extraneous lm in SDL_ttf

---

utils/build-all.sh

Makes it easier to tell if ports is failing to build in a scripted environment

Return error code when build failure occurs

---

lua/Makefile
lua/distinfo

- Everything checks out fine.
- There was a bugfix to the REPL with multiline input... and the REPL happens to be our only KOS example. What a coincidence!

Upgraded Lua to latest version 5.4.7.

---

mruby/files/KOSMakefile.mk

This PR follows up upon https://github.com/KallistiOS/KallistiOS/pull/613 for fixing mruby's install path for `mrbc`.
That one must be merged first.

Adjust mrbc install path in mrubyc port

---

utils/build-all.sh

@DC-SWAT reported an issue on MacOS from the changes in https://github.com/KallistiOS/kos-ports/pull/69. MacOS uses an older version of bash that doesn't recognize the `return` keyword to exit a script. Switching to `exit` should resolve this issue.

Fix unsupported bash for MacOS

---

libjpeg/Makefile

I was having issues building libjpeg (`ijg.org` was down), so I had to build it using a mirror.
Adding a mirror for future reference.

Add mirror for libjpeg

---

freetype/Makefile

Download from savannah gives problems sometimes, sourceforge is the official alt download url specified in http://freetype.org/download.html

Provide alt url for freetype

---

libvldmail/Makefile
libvldmail/pkg-descr

As on tin. This is a small library that tests an email address for being valid (a task that is significantly more complex than it would seem). I left the option for it to build its sample enabled as an extra test that it can be linked, though it would need modification to work correctly on the DC.

Add port for libvldmail

---

raylib4dc/Makefile

`raylib` won't build without `libGL` having been built.

Make raylib port depend on libGL port

---

.gitignore

Currently git will track the `build` and `dist` dirs if any ports were built.
This changes `.gitignore` so it no longer does that.

Adjust .gitignore to ignore build and dist dirs

---

scripts/download.mk

This change was requested by a few users. Similarly to [KallistiOS #525](https://github.com/KallistiOS/KallistiOS/pull/525)...
This cuts down drastically on the amount of data downloaded when building ports using git sources. Commit history is still downloaded so developers can `make fetch` sources and then checkout specific commit IDs, but the tree and blob data will be downloaded by the git client on demand in such case.

Use treeless clone when git repo is used as source

---

mruby/Makefile

As stated in the title, updating this port to use the [latest official release of mruby](https://github.com/mruby/mruby/tags).

`mruby`: bump to 3.3.0 release

---

expat/Makefile
libyaml/Makefile

When the KOS toolchain has been setup to build with flto expat will fail to link with the default ar and ranlib. So we'll use the gcc ones instead.

expat and libyaml: fix build with flto

---

SDL/files/SDL_dcevents.c

Here's the revived PR for the SDL keyboard changes that are required for the new keyboard API work: https://github.com/KallistiOS/KallistiOS/pull/503. 
~~PLEASE NOTE: The version guards currently assume `KOS_VERSION(2, 1, 1)`. Make sure they are changed to match whichever version this makes it into!~~
Talked to @QuzarDC and ensured it's now targetting KOS 2.2.0!

Reintroduced SDL changes for new kbd API.

---

freetype/Makefile
freetype/distinfo

bump to version 2.13.3
Release notes:
> The B/W rasterizer has become much faster; besides that, it is a maintenance release.
Full changelog:
> 
> CHANGES BETWEEN 2.13.2 and 2.13.3 (2024-Aug-11)
> 
>   **I. IMPORTANT CHANGES**
> 
>   - Some  fields  in  the  `FT_Outline` structure  have been   changed
>     from signed  to unsigned type,  which  better reflects  the actual
>     usage.   It  is  also  an  additional  means  to  protect  against
>     malformed input.
> 
> 
>   **II. IMPORTANT BUG FIXES**
> 
>   - Rare double-free crashes in the cache subsystem have been fixed.
> 
>   - Excessive stack allocation in the autohinter has been fixed.
> 
> 
>   **III. MISCELLANEOUS**
> 
>   - The B/W  rasterizer has  received a major  upkeep that  results in
>     large performance …

Update FreeType to version 2.13.3

---

zlib/files/KOSMakefile.mk
zlib/files/kos_zlib.c

zlib was implicitly getting fs_ calls from stdio before [KOS#995](https://github.com/KallistiOS/KallistiOS/pull/995). This makes the inclusion explicit. A second commit updated the makefile to ensure other includes were being appropriately accounted for.

Add missing include to kos_zlib.

---

lua/Makefile
lua/distinfo

- Bugfix version, although some of the bugs seem like a pretty big deal
(use-after-free, issues with raising errors in certain contexts, coroutines issue).
- Added better description for Lua KOS-port.

Updated Lua to version 5.4.8.

---

scripts/build.mk

The build system for kos-ports currently raw-dogs "cmake" as the command to build a CMakeLists.txt file, as opposed to our preferred "kos-cmake" wrapper file.
In addition to this requiring us to manually pass the toolchain argument for each invocation, it also means that should kos-cmake need to change in the future, the changes would not permeate out.
~~I just made a bugfix for DreamSDK which forces cmake to use the "Unix Makefiles" generator by explicitly passing it to cmake as part of the kos-cmake wrapper. This is required to ensure that CMake's top generator choice on Windows, freaking Visual Studio, does not get used when trying to build kos-ports.~~

build.mk script to use kos-cmake wrapper.

---

scripts/build.mk

The default CMake generator can be controlled by the CMAKE_GENERATOR environment variable. Therefore we cannot rely on the fact that CMake will generate Makefiles.
Update the build command so that it uses "cmake --build" instead.

scripts: Support non-Makefile CMake generators

---

mruby/Makefile
mruby/files/KOSMakefile.mk

This PR updates mruby:
- Removing hard-coded compiler options (e.g., `sh-elf-gcc`): calling KallistiOS wrappers (e.g., `kos-cc`, ...)
- Better detection of DreamSDK: handle both `ruby`/`rake` from Windows (i.e., from [RubyInstaller](https://rubyinstaller.org/)) and from [MSYS2](https://www.msys2.org/)
- Fix an issue while installing headers: sometimes, the includes were incorrectly modified to `mruby/mruby/mruby/<file.h>`. This is now fixed to update as `mruby/mruby/<file.h>`.
This PR fixes: https://github.com/KallistiOS/kos-ports/issues/113
See: https://github.com/mruby/mruby/pull/6600

`mruby`: remove hardcoded compiler options, improve DreamSDK detection, bug fix in header update

---

micropython/Makefile

Bump from **v1.21.0** to **v1.26.0**.
Fixes: https://github.com/KallistiOS/kos-ports/issues/112

`micropython`: bump to v1.26.0

---

libADX/Makefile

Bump from v1.0.0 to v1.0.1; fixes build warnings/issues.

`libADX`: Bump to v1.0.1

---

mruby/files/KOSMakefile.mk

On DreamSDK based on MinGW-w64/MSYS2, the `command -v rake` instruction doesn't work because the executable flag (`x`) isn't properly set. So we're testing the expected path directly (`/mingw64/bin/rake`).

`mruby`: improvement on `rake` detection

---

libmp3/files/KOSMakefile.mk

Newer versions of gcc (15+) default to the `c23`
which libmp3 would need quite a bit of work
to adapt to. For now, forcing it to build
with `-std=c17` to ensure it can build at all.
Closes #115

libmp3: Force building against `c17`
